-- Create feature_store, vitals_feature_store, documents_feature_store, notes_feature_store, and orders_feature_store tables in PostgreSQL.
-- Run with: psql postgresql://postgres:postgres@localhost:5432/feature_store -f scripts/init_feature_store.sql
-- Or (Docker): docker exec -i feature_store psql -U postgres -d feature_store < scripts/init_feature_store.sql

DROP TABLE IF EXISTS feature_store;

CREATE TABLE feature_store (
    patient_id TEXT PRIMARY KEY,
    mrn TEXT,
    cpmrn TEXT,
    encounters INTEGER,
    name TEXT,
    last_name TEXT,
    hospital_name TEXT,
    unit_name INTEGER,
    bed_no INTEGER,
    camera INTEGER,
    hospital_id TEXT,
    unit_id TEXT,
    command_center_id TEXT,
    age_year INTEGER,
    age_month INTEGER,
    age_days INTEGER,
    age_hour INTEGER,
    age_day INTEGER,
    age_minute INTEGER,
    dob DATE,
    sex TEXT,
    weight_unit TEXT,
    height_cm NUMERIC,
    weight_kg NUMERIC,
    ibw NUMERIC,
    bmi NUMERIC,
    birth_weight NUMERIC,
    birth_weight_unit TEXT,
    gestation_age_weeks INTEGER,
    gestation_age_days INTEGER,
    mother_info_name TEXT,
    mother_info_last_name TEXT,
    mother_info_blood_group TEXT,
    mother_info_lmp TEXT,
    mother_info_expected_delivery DATE,
    weight_history JSONB,
    icu_admit_date DATE,
    is_currently_admitted BOOLEAN,
    icu_discharge_date DATE,
    days INTEGER,
    vent_free_days INTEGER,
    apache_score NUMERIC,
    isolation JSONB,
    initial_symtoms JSONB,
    allergies JSONB,
    chief_complaint JSONB,
    other_complications JSONB,
    signs_at_admission JSONB,
    symptoms_at_admission JSONB,
    underlying_medical_conditions JSONB,
    chronic JSONB,
    immune JSONB,
    past_medical_history JSONB,
    diagnoses JSONB,
    documents TEXT[],
    vitals TEXT[],
    abnormal_vitals TEXT[],
    severity TEXT,
    transfer_history JSONB,
    orders TEXT[],
    completed_orders TEXT[],
    notes TEXT[],
    notes_diagnoses JSONB,
    notes_symptoms JSONB,
    notes_medications JSONB,
    notes_procedures JSONB,
    notes_tests JSONB
);

-- vitals_feature_store: vitals per patient / timestamp
DROP TABLE IF EXISTS vitals_feature_store;

CREATE TABLE vitals_feature_store (
    vital_id TEXT PRIMARY KEY,
    patient_id TEXT,
    timestamp DATE,
    therapy_device JSONB,
    vent_airway JSONB,
    temperature NUMERIC,
    temperature_unit TEXT,
    avpu TEXT,
    hr INTEGER,
    rr INTEGER,
    bp TEXT,
    reason_bp TEXT,
    map NUMERIC,
    cvp NUMERIC,
    sp_o2 INTEGER,
    fi_o2 INTEGER,
    pat_position TEXT,
    is_verified BOOLEAN,
    verified_time DATE,
    verified_by_name TEXT,
    verified_by_email TEXT,
    abnormal_fields TEXT[]
);

-- documents_feature_store: documents per patient
DROP TABLE IF EXISTS documents_feature_store;

CREATE TABLE documents_feature_store (
    document_id TEXT PRIMARY KEY,
    patient_id TEXT,
    is_inactive BOOLEAN,
    tags JSONB,
    secondary_keys JSONB,
    snomed_code JSONB,
    key TEXT,
    attributes JSONB,
    reported_at DATE,
    name TEXT,
    verified_at DATE,
    classifications JSONB,
    label TEXT
);

-- notes_feature_store: one row per component (composite PK)
DROP TABLE IF EXISTS notes_feature_store;

CREATE TABLE notes_feature_store (
    patient_id TEXT NOT NULL,
    note_id TEXT NOT NULL,
    content_id TEXT NOT NULL,
    component_id TEXT NOT NULL,
    PRIMARY KEY (patient_id, note_id, content_id, component_id),
    created_timestamp DATE,
    author TEXT,
    author_id TEXT,
    author_role TEXT,
    author_is_client BOOLEAN,
    note_type TEXT,
    note_sub_type TEXT,
    pend_or_signed TEXT,
    component_raw_value TEXT,
    component_parsed_text TEXT,
    is_delete_enabled BOOLEAN,
    chargeable TEXT,
    impact_case BOOLEAN,
    addendum_json JSONB,
    latest_addendum_author TEXT,
    latest_addendum_timestamp DATE,
    latest_addendum_text TEXT,
    note_diagnoses JSONB,
    note_symptoms JSONB,
    note_medications JSONB,
    note_procedures JSONB,
    note_tests JSONB,
    api_cost NUMERIC(12,6) DEFAULT 0
);

-- orders_feature_store: orders per patient
DROP TABLE IF EXISTS orders_feature_store;

CREATE TABLE orders_feature_store (
    order_id TEXT PRIMARY KEY,
    patient_id TEXT,
    order_no TEXT,
    lab_id TEXT,
    category TEXT,
    type TEXT,
    state TEXT,
    created_at DATE,
    updated_at DATE,
    signed TEXT,
    preset TEXT,
    orderable TEXT,
    protocol TEXT,
    history JSONB,
    additional_information TEXT,
    sos BOOLEAN,
    sos_reason TEXT,
    discontinue_reasons JSONB,
    discontinue_at DATE,
    discontinue_by TEXT,
    completed_at DATE,
    completed_by TEXT,
    urgency TEXT,
    start_time DATE,
    frequency JSONB,
    number_of_doses INTEGER,
    medication_pta BOOLEAN,
    medication_concentration JSONB,
    medication_combination JSONB,
    medication_name TEXT,
    medication_quantity INTEGER,
    medication_unit TEXT,
    medication_route TEXT,
    medication_no_of_days INTEGER,
    medication_form TEXT,
    medication_max_dose INTEGER,
    medication_body_weight INTEGER,
    labs_investigation TEXT,
    labs_discipline TEXT,
    labs_specimen_type TEXT,
    diets_name TEXT,
    diets_rate_value NUMERIC,
    diets_rate_unit TEXT,
    communications_gcs TEXT,
    communications_title TEXT,
    bloods_start_now BOOLEAN,
    bloods_time_period_detail JSONB,
    bloods_skip_schedule JSONB,
    bloods_title TEXT,
    bloods_quantity INTEGER,
    bloods_quantity_unit TEXT,
    bloods_schedule_selector TEXT,
    bloods_snomed_code INTEGER,
    procedure_name TEXT,
    procedure_ptype TEXT,
    procedure_laterality TEXT,
    procedure_site TEXT
);
